spring.application.name=CentroDeActividadesCEF

spring.datasource.url=jdbc:postgresql://db.kufazcrrdkqljytgwqeo.supabase.co:5432/postgres?sslmode=requirespring.datasource.username=postgres
spring.datasource.password=P5spUyjDcIbeL1f3
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.open-in-view=false