spring.application.name=CentroDeActividadesCEF

spring.datasource.url=${https://kufazcrrdkqljytgwqeo.supabase.co}
spring.datasource.username=${postgres}
spring.datasource.password=${P5spUyjDcIbeL1f3}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false